### ISSUE TITLE
Maybe a typo?

### ISSUE THREAD

**Issue by JAnthelme** [danjperron/PicoAudioPWM#10]
Hi, in wavePlayer.py, line 253, should it be `self.rightPWM.PWM_CC` instead of `self.leftPWM.PWM_CC`? Very helpful project, thanks a bunch!

**Comment by danjperron** [comment]
Hi,

 Long time that I didn’t check the code.


The left side is!

The DMA send both left and right data  so the left  is the first position address.

**Comment by JAnthelme** [comment]
Thank you. I realized that I did not understand properly the dma toggle part. I thought that each toggle woud alternatively feed the right data then the left data, not both of them.

**Comment by danjperron** [comment]
The way it works is an alternate buffer.

Automatically when one DMA is done the next buffer is used.  You have to set the next DMA when it’s running the current one.


Have a nice day.

Daniel

**Comment by JAnthelme** [comment]
thanks for taking the time, and thanks again for the project.
