### ISSUE TITLE
SPI does not work with WavePlayer

### ISSUE THREAD

**Issue by dmccreary** [danjperron/PicoAudioPWM#2]
Hello Dan,

Thank you for sharing your WavePlayer code with other RB2040 developers.  I am creating lessons for CoderDojo students learning Python.

I used your code to create a lesson for our students for playing WAV files:
https://www.coderdojotc.org/micropython/sound/07-play-audio-file/

The program worked very well as long as we did not use any SPI drivers with it.  Once we added an SPI display, the display stopped working.  I am not an expert, but I suspect that the DMA functions are using the same memory space as the SPI drivers.

I have tried using different DMA channels, but they all seem to have the same problem.

I put some sample test code here:

https://github.com/CoderDojoTC/micropython/blob/main/src/sound/display-test-wav.py

It is the following line that causes the display to become corrupt:

```py
player = wavePlayer(leftPin=Pin(LEFT_SPEAKER),rightPin=Pin(RIGHT_SPEAKER), dma0Channel=0, dma1Channel=1)
```

**Comment by danjperron** [comment]
Hi Dan,  I know  the issue that I don't lock the spi channel. Is not possible on Python.  Channel could be the issue.

But the chance are that the LCD spi is way too slow.  I will bet on it!  

Something to try,

-Use the second cpu in threads. I know that is not working very well. There are memory leakage issue.
- Modify the wave player to use interrupt.

I will check that but it will take some time. I'm working on my greenhouse system right now. 

Daniel
