### ISSUE TITLE
Clicks on start

### ISSUE THREAD

**Issue by couillonnade** [danjperron/PicoAudioPWM#3]
Hello Dan,

I have been testing your wavePlayer with success and was even able to boos the clock for 22 and 44kHz wav files.

The only problem I have now it the "click" when the was starts. My guess is that is comes from the PWM going from 0 to 1 initially. I have read somewhere that a workaround would be to set the output to average when nothing is played to avoid the click sound.

What I am trying to do is play short wav files based on an algorithm and each time I play a file I got that annoying click.

Can you confirm you have this as well and do you have any idea where to start looking at? Tried different Capacitors to smooth it but I did not succeed.

Thank you!

**Comment by danjperron** [comment]
Salut Rémi, 
       
      It is exactly this.  The click is from  the PWM 0 to 50%.   I didn't have that problem because I'm using an amplifier which has a capacitor. This make an high pass filter.  The other method is to add a ramp up header from 0% to 50%PWM. 
 A 0.1 sec ramp up should be enough.

**Comment by couillonnade** [comment]
OK, thanks for the confirmation of the 50%. So, I guess my high pass with the capacitor has some problem. Will have a look at it.

Do you have any pointer on where/how to add this ramp up in the code? Do you suggest I do that outside your code, before the play and then start the play?

**Comment by danjperron** [comment]
The wave file is 16bits signed.  Maybe set the IO to input and use two resistor to force the capacitor to be half voltage before starting the  wavefile and when the wave file is done.    The capacitor will be between the output and the signal out.
This will need some modification to the code. I can't do this test for at least a week.

Also, When I start the wave I force 50%PWM.  right now. This is ok if we add the thing I talk about on the first paragraph but right now it is a problem. To  get around it is to start at 0%PWm and add into the wave a 0.1 sec  buffer to get from 0% to the first wave signal value.

**Comment by couillonnade** [comment]
I see you set self.duty(self.top // 2) in the init of myPWM. It's actually the init that creates the clicks, not the start of the wav file.

Tried to be creative like this:

    def rampup(self, halfValue):
        value = 0
        increment = 1
        reg = mem32[self.PWM_CC]
        
        while value < halfValue:       
            if self.A_B == 0:
                # ok change channel A
                mem32[self.PWM_CC] = (reg & 0xffff0000) | value
            else:
                # channel channel B
                mem32[self.PWM_CC] = (reg & 0xffff) | (value << 16)
            value += increment
            utime.sleep_us(200)

and call it instead of setting to 50% but it's worse. Actually, just setting the duty to 0 create a louder click (for example changing line 34 to: self.duty(0) creates a massive click.

So I tried to isolate where does the problem comes from and found that the click is when setting the duty here:

super().duty_u16(32768)

which according to Raspberry Pico documentation is 50% duty.
Any other value, including 0, creates a loud click here.

So ramping up from 0 to half on base PWM class sounds not an option since duty at 0 creates a click.

I then tried to see what parameter is a problem in the initialization of the PWM and it's actually the frequency
Commenting the frequency line remove completely the click noise. Actually, commenting both frequency and duty has no side effect. It still plays correctly and there is no more click.

        super().__init__(pin)
        #super().freq(122_000)
        super().duty_u16(32768)

But, this is only true until I power off and power on the Raspberry Pico. When powered of, it goes to a state where there is some buz until the init of the PWM that clicks.

If I comment the 122_000 frequency and read the value, I get 122189. What's strange is setting the value to 122189, I read back 122549

super().freq(122189)
print(super().freq())

Anyway, I'm not sure it's something solvable. I don't see how a high pass filter would help here?

So I am planning on adding a transistor to act as a mute switch on the speaker line and activate it with a GPIO after the PWM is initialized.

**Comment by couillonnade** [comment]
Initial (power on) click is not something that can be fixed by soft since it's the clock start. Added hardware mute for boot to solve the issue when powering on the pico.
