### ISSUE TITLE
I get AttributeError: 'wavePlayer' object has no attribute 'dma0' error when trying player.stop() method

### ISSUE THREAD

**Issue by Gyges-of-lydia** [danjperron/PicoAudioPWM#4]
Hi,
the player plays .wav files correctly and its real awesome,
yet I encountered a problem I couldn't resolve,
I get "AttributeError: 'wavePlayer' object has no attribute 'dma0'" when ever I user the method player.stop()
I am not sure what am I missing,
Thanks in Advance,

**Comment by danjperron** [comment]
HI,

   The problem with python is that we couldn't reserved DMA channel.

This is why I'm using dma channel 10 and 11.

Try to use another ones.

Daniel

**Comment by Gyges-of-lydia** [comment]
It Worked! thank you very much!
btw, is there anyway to play the wav in the backgroud, whenever you issue palyer.play() method it plays the wav,
and get to the next line after the it done playing. I (fullishly) tried threading (im new to micro-controllers) but its not working on the pico of course, is there away to do it? Many thanks in advace!

**Comment by danjperron** [comment]
Hum,  maybe by interrupts when dma is empty.

 This will need more work .  I can't help you right now.

Daniel

**Comment by Gyges-of-lydia** [comment]
Thanks a ton!
