### ISSUE TITLE
Does it work with ESP32?

### ISSUE THREAD

**Issue by asherevan** [danjperron/PicoAudioPWM#8]
Do you happen to know if this library would work with ESP32?
I'm trying to make a portable audio device with it, and I'd like to know if this would work with it.

Thanks!

**Comment by danjperron** [comment]
Nope!

It is specifically  design for the pico.

Regards,

Daniel

**Comment by asherevan** [comment]
OK, thanks. Do you know of a library I could use instead? (Or how to modify this one to work with esp32)

**Comment by danjperron** [comment]
I never played with PWM on esp32.

Just google it!
https://espressif-docs.readthedocs-hosted.com/projects/espressif-esp-iot-solution/en/latest/audio/pwm_audio.html￼

Regards,
 Daniel

**Comment by asherevan** [comment]
Yes, I have tried googling it, but I couldn’t find anything for
MicroPython.
